#!/usr/bin/env python

# ######################################################
# snap 30 pictures while turning the rover in a circle
# ######################################################

import serial
import time
import numpy as np
import cv2
import sys
import os
import datetime

# open serial port for issuing motor commands

print "Reseting rover Arduino (opening serial port)"
ser = serial.Serial(port='/dev/ttyUSB0')
time.sleep(5)

print "Unlocking rover"
ser.write('G\n')

# start video capture device

capR = cv2.VideoCapture(0)
capL = cv2.VideoCapture(1)

print "Picture dimensions: %d x %d"%(capR.get(3),capR.get(4))

currdate=datetime.datetime.now()
picdir='/tmp/%s'%(datetime.datetime.strftime(currdate,'%Y%m%d-%H%M'))
os.makedirs(picdir)
os.chdir(picdir)

# start snapping pictures and turning right

npics=30

for counter in xrange(1,npics):

    print "Snapping picture pair %d/%d"%(counter,npics)
    retR, frameR = capR.read()
    retL, frameL = capL.read()
    cv2.imwrite("right%d.jpg"%(counter), frameR);
    cv2.imwrite("left%d.jpg"%(counter), frameL);
    counter+=1

    print "Panning"
    ser.write('L-5\n')
    ser.write('R5\n')
    time.sleep(0.2)
    ser.write('L-20\n')
    ser.write('R20\n')
    time.sleep(0.4)
    ser.write('L-5\n')
    ser.write('R5\n')
    time.sleep(0.2)
    ser.write('L0\n')
    ser.write('R0\n')

    print "Waiting 2s for stability"
    time.sleep(2)

print "Immobilizing rover"
ser.write('S\n')

print 'Uploading pictures'
os.system('scp -r %s galmasi@beeblebrox.almasi.org:/public/KubelWagen/'%(picdir))


print 'done'
